/**
 * Formation IA Territoriale - Base de Données des Exercices & Ateliers (60 Exercices)
 * Contient les énoncés, objectifs, types, supports, corrections et cheminements pédagogiques.
 */

const EXERCISES_DATABASE = [
    // === EXERCICES SUR PC (1 à 30) ===
    {
        id: 1,
        title: "Atelier Discours Municipal (Méthode M.A.I.R.E.)",
        support: "pc",
        format: "individuel",
        type: "pratique",
        time: 15,
        objective: "Rédiger un discours d'inauguration de gymnase structuré et calibré.",
        pedagogy: "Apprendre à formuler des consignes de rôle (persona), de ressources et de format pour un livrable de qualité publique.",
        instructions: "Rédigez un prompt pour demander à l'IA d'écrire le discours d'inauguration du gymnase municipal après sa rénovation énergétique. Intégrez les contraintes suivantes : travaux financés à 60% par la Région et 40% par la commune, focus sur la réduction de l'empreinte carbone, durée de lecture de 3 minutes.",
        solution: "Prompt modèle :\n[MOI] : Je suis le directeur de la communication d'une commune de 10 000 habitants.\n[AGENT] : Agis en plume politique expérimentée et spécialiste des discours républicains de proximité.\n[INFORMATION] : Rédige le discours que le Maire prononcera pour la réouverture du gymnase municipal rénové.\n[RESSOURCES] : Données de travaux : isolation par l'extérieur, chauffage biomasse, réduction de 50% de l'empreinte carbone. Financement : 60% Région, 40% Commune.\n[EXIGENCE] : Rédige un texte de 400 mots (environ 3 min de parole). Structure : Salutations officielles, remerciements aux financeurs, focus sur la transition écologique locale, conclusion républicaine positive. Ton solennel mais chaleureux.",
        reasoning: "Définir la plume politique donne le ton adéquat. Les ressources chiffrées évitent les inventions budgétaires. L'exigence de mots garantit le calibrage du temps de parole."
    },
    {
        id: 2,
        title: "Synthèse de Compte-Rendu de Réunion (DGS)",
        support: "pc",
        format: "individuel",
        type: "efficacite",
        time: 10,
        objective: "Résumer 2 pages de notes en 5 décisions clés et un tableau d'actions.",
        pedagogy: "Comprendre comment l'IA peut structurer des notes désorganisées en documents de synthèse professionnels et exploitables.",
        instructions: "Prenez des notes de réunion municipales brutes et demandez à l'IA de concevoir une note de synthèse avec 5 décisions stratégiques et un tableau d'actions (Qui, Quoi, Quand).",
        solution: "Prompt modèle :\n[MOI] : DGS de la collectivité.\n[AGENT] : Assistant administratif de direction expert en rédaction de synthèses.\n[INFORMATION] : Synthétise mes notes brutes de la réunion de projet 'Piste cyclable centre-ville' ci-dessous.\n[RESSOURCES] : [Copier-coller les notes brutes de réunion]\n[EXIGENCE] : Structure en 2 parties : 1) Les 5 décisions clés prises (sous forme de liste à puces), 2) Un tableau récapitulatif des actions avec les colonnes : Responsable, Action à mener, Échéance. Évite le jargon inutile, reste ultra-synthétique.",
        reasoning: "L'IA excelle à re-structurer le texte non ordonné. Demander un tableau d'actions force l'IA à extraire des responsabilités précises de manière opérationnelle."
    },
    {
        id: 3,
        title: "Traduction de la Charte d'Accueil en 3 langues",
        support: "pc",
        format: "individuel",
        type: "pratique",
        time: 10,
        objective: "Traduire un texte administratif en anglais, espagnol et arabe en conservant la politesse.",
        pedagogy: "Maîtriser les capacités multilingues des LLM pour améliorer l'accueil du public non francophone.",
        instructions: "Rédigez un prompt pour traduire le protocole d'accueil de la mairie (gestion des files d'attente, pièces justificatives à préparer) en 3 langues, en veillant à ce que le ton reste courtois et accueillant.",
        solution: "Prompt modèle :\n[MOI] : Responsable du service des relations aux usagers.\n[AGENT] : Traducteur professionnel spécialisé dans les administrations publiques.\n[INFORMATION] : Traduis la charte d'accueil ci-dessous en anglais, espagnol et arabe.\n[RESSOURCES] : [Coller le texte de la charte d'accueil municipal]\n[EXIGENCE] : Conserve un ton très poli, chaleureux et institutionnel. Présente les traductions les unes à la suite des autres, séparées par des titres clairs.",
        reasoning: "Préciser le contexte d'administration publique empêche l'IA d'utiliser des termes trop commerciaux ou familiers lors de la traduction sémantique."
    },
    {
        id: 4,
        title: "Analyse Comparative de 3 Devis Informatiques",
        support: "pc",
        format: "individuel",
        type: "efficacite",
        time: 15,
        objective: "Établir un tableau comparatif financier et technique de 3 offres d'achat.",
        pedagogy: "Gagner du temps sur l'analyse de dossiers de marchés publics en structurant les écarts d'offres.",
        instructions: "Collez le résumé de 3 devis d'achat d'ordinateurs pour les écoles dans le prompt et demandez à l'IA de générer un tableau comparatif HT/TTC, durée de garantie et points d'attention.",
        solution: "Prompt modèle :\n[MOI] : Acheteur public de la collectivité.\n[AGENT] : Analyste financier et expert en marchés publics.\n[INFORMATION] : Analyse et compare les 3 offres d'ordinateurs scolaires fournies en ressources.\n[RESSOURCES] : Offre A (15 ordinateurs, 500€ HT/unité, garantie 1 an). Offre B (15 ordinateurs, 530€ HT/unité, garantie 3 ans, livraison offerte). Offre C (15 ordinateurs, 480€ HT/unité, garantie 1 an, installation 500€ HT).\n[EXIGENCE] : Génère un tableau comparatif avec : Nom de l'offre, Coût unitaire HT, Coût total HT, Coût total TTC (TVA 20%), Durée de la garantie, Avantages techniques, Inconvénients. Termine par une recommandation motivée de 3 lignes.",
        reasoning: "Les calculs financiers de base et l'analyse de critères multiples permettent à l'IA de dégager l'offre économiquement la plus avantageuse (ici l'Offre B sur 3 ans)."
    },
    {
        id: 5,
        title: "Désescalade Écrite (Réponse à un administré agressif)",
        support: "pc",
        format: "individuel",
        type: "pratique",
        time: 10,
        objective: "Rédiger un courriel de réponse ferme mais apaisant et neutre.",
        pedagogy: "Apprendre à désamorcer les conflits écrits en utilisant l'IA pour reformuler des sentiments hostiles en termes factuels et professionnels.",
        instructions: "Copiez un e-mail d'administré en colère se plaignant d'un retard de travaux. Demandez à l'IA d'analyser ses griefs et de rédiger une réponse constructive en évitant les termes défensifs.",
        solution: "Prompt modèle :\n[MOI] : Responsable de la relation usagers.\n[AGENT] : Expert en médiation de conflits et communication non violente en secteur public.\n[INFORMATION] : Rédige un courriel de réponse à l'e-mail d'insatisfaction ci-dessous.\n[RESSOURCES] : [Coller l'e-mail énervé de l'administré]\n[EXIGENCE] : Ne réponds pas sur le ton de la colère. Reste factuel, exprime de l'empathie pour la gêne occasionnée sans rejeter la faute sur les agents. Explique que les travaux se terminent le 15 juin. Longueur max : 150 mots.",
        reasoning: "Le filtre d'empathie de l'IA élimine la réactivité émotionnelle de l'agent fatigué et permet de rédiger un texte conforme à la charte de neutralité publique."
    },
    {
        id: 6,
        title: "Communication Événementielle (Fête de la Musique)",
        support: "pc",
        format: "individuel",
        type: "fun",
        time: 10,
        objective: "Concevoir une série de posts accrocheurs et humoristiques pour les réseaux sociaux.",
        pedagogy: "Utiliser la créativité (température élevée) de l'IA pour diversifier les styles de communication sur les réseaux sociaux municipaux.",
        instructions: "Créez 3 variantes de posts Facebook pour annoncer la Fête de la Musique municipale : un ton officiel, un ton jeune et décalé, et un ton sous forme de devinettes.",
        solution: "Prompt modèle :\n[MOI] : Chargé de communication numérique de la ville.\n[AGENT] : Community manager créatif spécialisé dans le secteur territorial.\n[INFORMATION] : Génère 3 propositions de posts pour promouvoir la fête de la musique du 21 juin sur la place de la mairie.\n[EXIGENCE] : Post 1 : Institutionnel et informatif (horaires, sécurité). Post 2 : Humour et références musicales décalées. Post 3 : Sous forme de rébus ou de devinette pour engager les habitants. Utilise des emojis adaptés.",
        reasoning: "Varier les personas et les styles éditoriaux montre que l'IA peut s'adapter à des cibles très différentes (de l'élu aux adolescents de la commune)."
    },
    {
        id: 7,
        title: "Extraction de Données Budgétaires Brutes",
        support: "pc",
        format: "individuel",
        type: "efficacite",
        time: 15,
        objective: "Nettoyer un texte budgétaire pour en faire un tableau CSV propre.",
        pedagogy: "Apprendre à faire extraire des entités structurées à partir d'un flux de texte désordonné.",
        instructions: "Collez un paragraphe décousu de chiffres budgétaires de fonctionnement et demandez à l'IA d'en extraire les recettes et dépenses dans un format tabulaire prêt pour Excel.",
        solution: "Prompt modèle :\n[MOI] : Comptable de la collectivité.\n[AGENT] : Data analyst expert en comptabilité publique (M57).\n[INFORMATION] : Extrais toutes les données financières du texte brut en ressources pour en faire un tableau structuré.\n[RESSOURCES] : [Coller le texte budgétaire brut, ex: 'On note 12k€ de fournitures scolaires, 45k€ de chauffage et une recette de subvention de 18k€...']\n[EXIGENCE] : Structure en tableau avec : Catégorie (Dépense/Recette), Poste comptable, Montant en euros. Ne rajoute aucun commentaire introductif ou conclusif.",
        reasoning: "L'IA applique des filtres regex internes pour extraire les valeurs associées à des concepts, évitant la saisie manuelle fastidieuse."
    },
    {
        id: 8,
        title: "Atelier FAQ d'Accueil (Demandes de Passeport)",
        support: "pc",
        format: "individuel",
        type: "pratique",
        time: 15,
        objective: "Générer une foire aux questions claire sur les démarches administratives.",
        pedagogy: "Utiliser l'IA pour vulgariser des textes administratifs complexes (du site Service-Public) en questions-réponses simples pour les usagers.",
        instructions: "Prenez les règles officielles d'obtention du passeport pour un mineur et demandez à l'IA de rédiger une FAQ de 5 questions courantes sous forme de dépliant.",
        solution: "Prompt modèle :\n[MOI] : Agent d'accueil en mairie.\n[AGENT] : Rédacteur web spécialisé dans la simplification des démarches administratives (FALC).\n[INFORMATION] : Rédige une FAQ de 5 questions sur l'obtention d'un passeport pour un mineur à partir des règles officielles ci-dessous.\n[RESSOURCES] : [Coller le texte officiel ou le lien de documentation]\n[EXIGENCE] : Rédige des questions du point de vue du parent (ex: 'Mon enfant doit-il être présent ?'). Les réponses doivent être courtes, à puces et très claires. Indique la liste des documents requis.",
        reasoning: "La vulgarisation (rendre simple ce qui est légalement complexe) est une des forces majeures des LLM, à condition de leur fournir la ressource légale de départ (ancrage)."
    },
    {
        id: 9,
        title: "Poème du Tri Sélectif (Sensibilisation Écoles)",
        support: "pc",
        format: "individuel",
        type: "fun",
        time: 10,
        objective: "Créer une chanson ou un poème court pour sensibiliser les enfants au tri des déchets.",
        pedagogy: "Explorer les capacités poétiques et métaphoriques de l'IA pour créer des supports d'animation ludiques.",
        instructions: "Demandez à l'IA d'écrire une poésie rimée de 4 strophes expliquant aux enfants de CM1 pourquoi le plastique va dans la poubelle jaune et le verre dans le bac vert.",
        solution: "Prompt modèle :\n[MOI] : Animateur périscolaire.\n[AGENT] : Poète pour enfants et éducateur en développement durable.\n[INFORMATION] : Rédige un poème rimé pédagogique pour apprendre le tri sélectif aux enfants de 8-10 ans.\n[EXIGENCE] : 4 strophes en rimes croisées (ABAB). Explique la destination de la poubelle jaune (plastique, carton) et du bac vert (bouteilles en verre). Utilise un vocabulaire joyeux et mémorisable.",
        reasoning: "Les contraintes de rimes et de rythme forcent l'IA à piocher dans ses vecteurs lexicaux de sonorité, montrant sa flexibilité créative."
    },
    {
        id: 10,
        title: "Plan de Végétalisation d'un Parvis Municipal",
        support: "pc",
        format: "individuel",
        type: "pratique",
        time: 15,
        objective: "Établir une liste de plantes adaptées à la sécheresse avec leurs fiches techniques.",
        pedagogy: "Associer des contraintes d'aménagement urbain et environnemental pour générer un plan technique structuré.",
        instructions: "Concevez un prompt pour demander une palette végétale de 5 plantes méditerranéennes ou résistantes, mellifères, nécessitant peu d'eau, pour réaménager le parvis de la mairie du Sud.",
        solution: "Prompt modèle :\n[MOI] : Responsable des espaces verts d'une commune soumise aux restrictions d'eau d'été.\n[AGENT] : Architecte paysagiste expert en xéropaysagisme (jardin sans eau) et biodiversité.\n[INFORMATION] : Propose 5 espèces de plantes pour notre parvis ensoleillé.\n[EXIGENCE] : Pour chaque plante, indique : Nom commun, Nom latin, Besoins en eau (sur 5), Période de floraison, Rôle écologique (ex. pollinisateurs). Présente sous forme de tableau Markdown.",
        reasoning: "Le typage des sorties (tableau Markdown) permet d'insérer directement le rendu dans une note technique d'élus."
    },
    {
        id: 11,
        title: "Note de Cadrage Projet (Raccordement Fibre)",
        support: "pc",
        format: "individuel",
        type: "efficacite",
        time: 15,
        objective: "Rédiger une note de cadrage technique et méthodologique de 2 pages.",
        pedagogy: "Utiliser l'IA pour générer la structure et le premier jet d'une note de projet complexe en interne.",
        instructions: "Demandez à l'IA de concevoir le plan détaillé et le contenu d'une note de cadrage pour les travaux de raccordement de la fibre optique dans le hameau isolé de la commune.",
        solution: "Prompt modèle :\n[MOI] : Directeur des Services Techniques.\n[AGENT] : Consultant en gestion de projets d'infrastructures télécoms.\n[INFORMATION] : Rédige le plan et le texte de cadrage pour le projet de déploiement de la fibre au Hameau des Chênes.\n[RESSOURCES] : Longueur du câble : 2 km, 50 foyers concernés, budget estimé de 40k€, début des travaux en septembre, durée 3 mois.\n[EXIGENCE] : Rédige une note structurée en 5 parties : 1) Contexte et objectifs, 2) Spécifications techniques et calendrier, 3) Budget et partenaires financiers, 4) Risques identifiés (intempéries, retards de livraison), 5) Plan de communication aux habitants. Ton professionnel et neutre.",
        reasoning: "Définir les risques (intempéries/délais) montre la capacité de l'IA à projeter des variables externes sur un projet à partir de sa base générale de connaissances."
    },
    {
        id: 12,
        title: "Requête SQL pour listing Cantines Scolaires",
        support: "pc",
        format: "individuel",
        type: "pratique",
        time: 15,
        objective: "Écrire une requête de base de données sans compétence de code préalable.",
        pedagogy: "Démontrer comment un agent non technicien peut générer du code informatique (SQL) pour extraire des informations d'un progiciel métier.",
        instructions: "Vous devez extraire la liste des élèves allergiques inscrits à la cantine de l'école Pasteur. Rédigez un prompt pour demander à l'IA de concevoir la requête SQL correspondante à partir de la structure de vos tables.",
        solution: "Prompt modèle :\n[MOI] : Agent administratif du service scolaire de la mairie.\n[AGENT] : Développeur SQL sénior spécialisé dans les bases de données de gestion éducative.\n[INFORMATION] : Rédige une requête SQL pour lister les élèves.\n[RESSOURCES] : Tables : 'eleves' (colonnes: id, nom, prenom, classe, ecole) et 'cantine' (colonnes: id_eleve, inscrit_oui_non, allergie_details).\n[EXIGENCE] : La requête SQL doit lister le nom, prénom et classe des élèves de l'école 'Pasteur' inscrits à la cantine (inscrit_oui_non = 'OUI') et ayant des allergies (allergie_details non vide). Ajoute des commentaires explicatifs pour chaque ligne de code SQL.",
        reasoning: "L'IA traduit le langage naturel en syntaxe logique stricte (SQL), ce qui permet à des agents non techniques de dialoguer avec la DSI pour obtenir des extractions spécifiques."
    },
    {
        id: 13,
        title: "Chasse aux Hallucinations Juridiques (CGCT)",
        support: "pc",
        format: "individuel",
        type: "efficacite",
        time: 15,
        objective: "Identifier des erreurs insérées délibérément dans une réponse d'IA sur le code des collectivités.",
        pedagogy: "Développer le réflexe d'esprit critique et de vérification des sources légales (recherche sur Légifrance) face à une réponse d'IA.",
        instructions: "Demandez à l'IA de citer l'article du Code Général des Collectivités Territoriales (CGCT) régissant le droit d'expression des élus d'opposition dans le magazine municipal. Allez vérifier sur Légifrance si le numéro d'article et la citation exacte correspondent à la réalité.",
        solution: "Prompt type : 'Quel article du CGCT régit le droit d'expression des élus minoritaires dans les bulletins d'information ? Donne le texte exact.'\nRésultat attendu : L'IA peut citer l'article L. 2121-27-1. Le stagiaire doit ouvrir Légifrance, taper cet article et comparer mot à mot la réponse de l'IA pour vérifier s'il n'y a pas d'hallucination (ex: invention de l'obligation pour les communes de moins de 1000 habitants).",
        reasoning: "Cet exercice confronte les stagiaires à la réalité physique de la génération statistique : l'IA peut affirmer un numéro d'article faux avec une assurance rédactionnelle totale."
    },
    {
        id: 14,
        title: "Atelier Charte de Télétravail Interne",
        support: "pc",
        format: "individuel",
        type: "pratique",
        time: 20,
        objective: "Créer un accord-cadre de télétravail conforme aux règles de la fonction publique.",
        pedagogy: "Utiliser l'IA pour structurer un document de ressources humaines complexe nécessitant de respecter des règles législatives préexistantes.",
        instructions: "Rédigez un prompt pour concevoir une charte du télétravail pour les agents de votre commune. Intégrez les règles suivantes : 2 jours maximum par semaine, obligation de présence le mardi, non-éligibilité des agents d'accueil physique.",
        solution: "Prompt modèle :\n[MOI] : Responsable des Ressources Humaines en mairie.\n[AGENT] : Expert en droit du travail de la fonction publique territoriale.\n[INFORMATION] : Rédige une charte de télétravail pour notre collectivité.\n[RESSOURCES] : Accord national cadre de 2021 sur le télétravail dans la fonction publique. Contraintes internes : Max 2 jours/semaine, mardi présentiel obligatoire, agents d'accueil physique exclus.\n[EXIGENCE] : Rédige le texte sous forme d'articles de loi structurés (Art. 1 : Éligibilité, Art. 2 : Demande et acceptation, Art. 3 : Temps de travail et déconnexion, Art. 4 : Équipements). Ton neutre et juridique.",
        reasoning: "L'IA utilise sa connaissance des formats juridiques classiques pour structurer un accord RH clair et exploitable lors des comités sociaux territoriaux (CST)."
    },
    {
        id: 15,
        title: "Brainstorming Noms d'Éco-Quartiers",
        support: "pc",
        format: "individuel",
        type: "fun",
        time: 10,
        objective: "Générer des idées de noms évocateurs pour un nouveau projet d'urbanisme durable.",
        pedagogy: "Utiliser l'IA comme outil d'idéation et de créativité pour sortir des sentiers battus.",
        instructions: "Demandez à l'IA de proposer 15 noms poétiques et évocateurs pour un éco-quartier construit autour d'une ancienne filature de coton, valorisant l'eau et la biodiversité locale.",
        solution: "Prompt modèle :\n[MOI] : Chef de projet urbanisme.\n[AGENT] : Concepteur-rédacteur créatif spécialisé en branding et marketing territorial.\n[INFORMATION] : Propose 15 noms originaux pour notre futur éco-quartier.\n[RESSOURCES] : Contexte : ancienne usine de coton historique, présence d'un canal, chaufferie bois, parc urbain de 2 hectares.\n[EXIGENCE] : Propose des noms qui lient l'histoire industrielle et la transition écologique (ex: 'Les Tissages Verts', 'Le Parvis du Canal'). Classe-les par thématiques (Historique, Nature, Avenir).",
        reasoning: "L'IA combine des concepts éloignés (industrie textile et écologie) pour créer des métaphores verbales nouvelles, ce qui stimule la créativité des équipes projets."
    },
    {
        id: 16,
        title: "Rédaction d'un Communiqué d'Alerte Canicule",
        support: "pc",
        format: "individuel",
        type: "efficacite",
        time: 10,
        objective: "Concevoir un communiqué de crise clair destiné à la presse et aux habitants.",
        pedagogy: "Apprendre à réagir dans l'urgence en créant un document de communication publique officiel en quelques minutes.",
        instructions: "Le département passe en alerte rouge canicule. Créez un prompt pour générer le communiqué officiel de la mairie listant les mesures de sécurité et l'ouverture des salles climatisées.",
        solution: "Prompt modèle :\n[MOI] : Directeur de cabinet du Maire.\n[AGENT] : Responsable de la communication de crise publique.\n[INFORMATION] : Rédige en urgence un communiqué de presse d'alerte canicule.\n[RESSOURCES] : Préfecture : alerte rouge. Mesures mairie : ouverture du foyer climatisé des aînés de 10h à 18h, activation du registre des personnes vulnérables, annulation des activités sportives extérieures.\n[EXIGENCE] : Rédige un texte court de 250 mots maximum. Utilise des consignes de sécurité claires sous forme de liste. Donne le numéro de téléphone d'urgence de la mairie. Ton calme, protecteur et rigoureux.",
        reasoning: "En cas d'urgence, la rapidité d'exécution de l'IA évite le stress de la mise en page et de la formulation de base, laissant aux agents le temps de valider et de diffuser."
    },
    {
        id: 17,
        title: "Simplification administrative (FALC) d'un décret",
        support: "pc",
        format: "individuel",
        type: "pratique",
        time: 15,
        objective: "Traduire un texte législatif complexe en français Facile à Lire et à Comprendre.",
        pedagogy: "Garantir l'accessibilité de l'information publique en utilisant l'IA comme traductrice simplifiée pour les usagers en situation de handicap ou allophones.",
        instructions: "Prenez l'article de loi concernant l'attribution de l'Allocation Personnalisée d'Autonomie (APA) et demandez à l'IA de le réécrire en respectant la charte européenne du FALC (mots simples, phrases courtes, une idée par ligne).",
        solution: "Prompt modèle :\n[MOI] : Conseiller en espace d'accès aux droits sociaux.\n[AGENT] : Rédacteur expert en accessibilité et en méthodologie FALC (Facile à Lire et à Comprendre).\n[INFORMATION] : Réécris le texte officiel en ressources en français simplifié FALC.\n[RESSOURCES] : [Coller le décret officiel sur l'attribution de l'APA]\n[EXIGENCE] : Fais des phrases de maximum 10 mots. Utilise des verbes d'action au présent. Supprime les termes juridiques complexes ou explique-les immédiatement entre parenthèses. Fais une liste à puces pour les critères d'âge et de santé.",
        reasoning: "La simplification sémantique est un processus mécanique de réduction de complexité syntaxique pour lequel l'IA obtient d'excellents résultats, facilitant l'accès universel aux droits."
    },
    {
        id: 18,
        title: "Gabarits de Mail pour l'État Civil (Mariages)",
        support: "pc",
        format: "individuel",
        type: "efficacite",
        time: 10,
        objective: "Créer un ensemble de mails types pour relancer les dossiers de mariage incomplets.",
        pedagogy: "Gagner du temps sur les tâches répétitives en automatisant les courriels quotidiens tout en préservant la cordialité du service public.",
        instructions: "Concevez un prompt pour générer 3 modèles de mails types à destination des futurs époux : dossier incomplet (pièce d'identité manquante), confirmation de la date et de l'heure, et rappel des règles de sécurité (retards, stationnement).",
        solution: "Prompt modèle :\n[MOI] : Agent d'état civil.\n[AGENT] : Rédacteur en relations publiques courtoises.\n[INFORMATION] : Génère 3 gabarits de mails types pour les dossiers de mariage.\n[EXIGENCE] : Mail 1 : Demande polie mais ferme de la pièce d'identité manquante pour valider le dossier. Mail 2 : Message de félicitations et confirmation du créneau (Samedi 14 septembre à 11h). Mail 3 : Rappel des consignes de civilité (pas de jets de riz en plastique sur le parvis, stationnement limité). Conserve des balises modifiables comme [NOM_EPOUX] ou [DATE] dans les textes.",
        reasoning: "Les modèles de courriels rédigés par l'IA permettent d'unifier la qualité de la relation usagers au sein de l'équipe d'état civil."
    },
    {
        id: 19,
        title: "Atelier RAG : Règlement Cantine Incassable",
        support: "pc",
        format: "individuel",
        type: "pratique",
        time: 15,
        objective: "Forcer l'IA à répondre à une question uniquement à l'aide d'un texte fourni, sans inventer.",
        pedagogy: "Comprendre et appliquer le mécanisme d'ancrage (RAG) pour éviter les hallucinations et garantir la fidélité légale.",
        instructions: "Collez le règlement de la cantine scolaire dans le prompt. Posez la question : 'Un enfant peut-il manger de la viande s'il a un certificat médical d'allergie au poisson ?' Ajoutez la consigne stricte de verrouillage de recherche.",
        solution: "Prompt modèle :\n[MOI] : Agent d'accueil scolaire.\n[AGENT] : Assistant d'information factuelle qui se base uniquement sur le texte ci-dessous.\n[INFORMATION] : Réponds à la question suivante : 'Quel est le protocole si un enfant arrive en retard à la cantine ?'\n[RESSOURCES] : [Coller l'intégralité du règlement cantine]\n[EXIGENCE] : Ne réponds que si la réponse exacte figure dans le règlement ci-dessus. Si l'information n'y est pas écrite, réponds exclusivement : 'Je ne sais pas car cela n'est pas précisé dans le document'. N'invente rien.",
        reasoning: "L'ancrage strict montre comment inhiber la mémoire générale du réseau de neurones au profit d'une base de connaissances documentaire de confiance."
    },
    {
        id: 20,
        title: "Recherche de subventions d'État (Comparatif)",
        support: "pc",
        format: "individuel",
        type: "efficacite",
        time: 20,
        objective: "Trouver et comparer les dispositifs d'aides de l'État pour l'achat de vélos électriques municipaux.",
        pedagogy: "Utiliser les fonctions de recherche connectée au web de l'IA (ex. Gemini/ChatGPT Web) pour effectuer une veille sur les aides publiques régionales et étatiques.",
        instructions: "Utilisez une IA avec accès internet pour chercher les dispositifs d'aide financière actuels en France pour l'achat d'une flotte de vélos à assistance électrique (VAE) par une collectivité territoriale. Synthétisez sous forme de liste.",
        solution: "Prompt modèle :\n[MOI] : Directeur financier de commune.\n[AGENT] : Veilleur stratégique spécialisé en subventions publiques et transition écologique.\n[INFORMATION] : Recherche sur internet les subventions nationales et régionales actives en 2026 pour l'achat de vélos à assistance électrique par une mairie.\n[EXIGENCE] : Fais la liste des aides (ex: Bonus Vélo, aides ADEME, subventions de la Région). Indique pour chaque aide : le taux de cofinancement maximum, les critères d'éligibilité et le lien officiel vers le guichet de dépôt. Cite tes sources.",
        reasoning: "La recherche active avec l'IA permet d'agréger des informations dispersées sur plusieurs sites étatiques en un seul tableau de synthèse à jour."
    },
    {
        id: 21,
        title: "Atelier Groupe : L'Organisateur de Séminaire",
        support: "pc",
        format: "groupe",
        type: "efficacite",
        time: 30,
        objective: "Concevoir le programme logistique d'une journée d'intégration pour 50 agents.",
        pedagogy: "Travailler la planification collaborative en confiant la logistique et les plannings à l'IA pour libérer le temps de réflexion stratégique de l'équipe.",
        instructions: "En équipe de 3, utilisez l'IA pour planifier la journée d'intégration des 50 nouveaux agents de la métropole. Demandez un déroulé horaire, la gestion des repas, un atelier brise-glace et la gestion du budget global (limité à 2000 €).",
        solution: "Cheminement du groupe :\n1. Écrire le prompt d'objectifs (50 agents, budget 2000€, 9h-17h, thématique cohésion).\n2. Demander à l'IA des propositions d'ateliers et de traiteur.\n3. Affiner en demandant à l'IA d'optimiser le budget (ex: réduire le coût du traiteur pour acheter des lots de récompenses).\n4. Exporter le planning horaire final sous forme de tableau.",
        reasoning: "L'IA agit comme un secrétaire de projet instantané qui calcule la répartition des enveloppes budgétaires et propose des déroulés d'ateliers logiques (alternance théorie/pratique)."
    },
    {
        id: 22,
        title: "Atelier Groupe : Le Prompt Système d'un Chatbot d'Accueil",
        support: "pc",
        format: "groupe",
        type: "pratique",
        time: 30,
        objective: "Écrire les consignes système (garde-fous) d'une IA d'accueil usagers pour le site web.",
        pedagogy: "Comprendre comment configurer l'identité d'un agent public virtuel (Chatbot) pour qu'il reste neutre, poli et ne donne pas de faux conseils juridiques.",
        instructions: "En groupe, rédigez le 'System Prompt' (le rôle invisible de base) d'un agent conversationnel de mairie. L'IA doit guider l'usager sur les horaires, ne jamais prendre de décision de droit, et s'adresser poliment aux citoyens.",
        solution: "Proposition de System Prompt rédigé par les stagiaires :\n'Tu es l'agent virtuel officiel de la Mairie de [Nom]. Ta mission est d'orienter les usagers sur les horaires d'ouverture (Lu-Ve, 8h30-17h00) et les pièces à fournir pour les démarches courantes. Règle 1 : Reste toujours poli, neutre politiquement et bienveillant. Règle 2 : Ne donne jamais d'avis juridique ou de promesse d'attribution d'aide. Règle 3 : Si tu ne sais pas, renvoie vers le numéro d'accueil standard.'",
        reasoning: "Cet exercice montre l'importance des consignes racines (System Prompt) pour brider les réponses d'un robot orienté vers le grand public."
    },
    {
        id: 23,
        title: "Atelier Groupe : Le Hackathon de l'Efficacité Administrative",
        support: "pc",
        format: "groupe",
        type: "efficacite",
        time: 45,
        objective: "Mesurer et optimiser le temps passé sur une tâche administrative classique en binôme.",
        pedagogy: "Comparer l'efficacité humaine brute et l'efficacité augmentée par l'IA sur un travail concret de rédaction de délibération.",
        instructions: "Un stagiaire rédige une délibération d'attribution de subvention de manière classique (en cherchant les modèles de textes sur son PC). L'autre utilise l'IA pour générer le brouillon à partir d'un prompt structuré. Comparez le temps nécessaire et la qualité finale du document.",
        solution: "Cheminement de l'atelier :\n1. Agent A (sans IA) : Ouvre Word, cherche un vieux modèle, modifie les champs. Temps moyen observé : 20 minutes.\n2. Agent B (avec IA) : Rédige un prompt avec la méthode MAIRE en insérant les données financières. Relecture et ajustement. Temps moyen : 5 minutes.\n3. Analyse : Gain de temps de 75%. Discussion sur le fait que la relecture humaine par l'Agent B est l'étape cruciale pour valider les formules de visas légaux (ex. 'Vu le Code Général...').",
        reasoning: "La preuve par la pratique : les stagiaires constatent physiquement la réduction drastique du temps de rédaction administrative et le déplacement de leur valeur ajoutée de la saisie vers la relecture."
    },
    {
        id: 24,
        title: "Atelier Groupe : Co-Rédaction d'un Plan Climat Local",
        support: "pc",
        format: "groupe",
        type: "pratique",
        time: 40,
        objective: "Élaborer une note d'orientation stratégique environnementale en mode interactif avec l'IA.",
        pedagogy: "Apprendre à dialoguer par itérations successives avec l'IA pour affiner un projet de service public.",
        instructions: "En groupes de 3, concevez les 5 axes majeurs du Plan Climat Air Énergie Territorial (PCAET) de votre commune. Ne demandez pas tout en un seul prompt : commencez par brainstormer les axes généraux, puis demandez des détails sur l'axe 1, puis des idées d'indicateurs financiers.",
        solution: "Déroulement de la co-rédaction :\n1. Étape 1 : Rédiger un prompt d'idées générales. L'IA propose 10 axes.\n2. Étape 2 : Le groupe choisit 5 axes et demande à l'IA d'approfondir l'axe 'Rénovation thermique des bâtiments publics'.\n3. Étape 3 : Demander à l'IA des indicateurs de suivi (ex. m3 d'eau économisés, tonnes de CO2 évitées).\n4. Étape 4 : Demander la synthèse finale sous forme de note de présentation pour le Conseil Municipal.",
        reasoning: "Le mode itératif évite le syndrome du 'prompt magique' unique. Il montre que l'IA fonctionne comme un copilote de réflexion avec qui on affine un document étape par étape."
    },
    {
        id: 25,
        title: "Atelier Groupe : Le Jeu de l'IA Stupide",
        support: "pc",
        format: "groupe",
        type: "fun",
        time: 20,
        objective: "Comprendre les limites sémantiques de l'IA en jouant le rôle de la machine.",
        pedagogy: "Prendre conscience du fait que l'IA n'a aucune intuition humaine et applique les prompts de manière littérale et parfois absurde.",
        instructions: "Le Groupe A rédige un prompt pour demander à dessiner ou écrire une procédure (ex: 'Faire une tasse de café'). Le Groupe B joue le rôle de l'IA et doit appliquer le prompt de manière strictement littérale, sans utiliser le bon sens (si le prompt ne mentionne pas d'ouvrir le placard pour prendre la tasse, le Groupe B fait mine de verser le café sur la table). Estimez les oublis du prompt.",
        solution: "Exemple d'exercice :\nSi le prompt dit : 'Prends la cafetière, verse l'eau dans le filtre et mets le café en route'. L'IA humaine va verser l'eau sur le café moulu sec sans l'avoir mis dans la cafetière, car le prompt a oublié de dire 'ouvre le couvercle de la cafetière'.\nLeçon : Un prompt doit guider l'IA étape par étape, sans présupposer qu'elle connaît le contexte implicite de la pièce.",
        reasoning: "Cette expérience ludique montre que l'ordinateur est un exécutant aveugle. Plus les instructions manquent de précision contextuelle, plus le résultat est erroné."
    },
    {
        id: 26,
        title: "Atelier Groupe : Nettoyage de Prompts (Audit RGPD)",
        support: "pc",
        format: "groupe",
        type: "pratique",
        time: 30,
        objective: "Identifier et supprimer les données nominatives dans des prompts complexes.",
        pedagogy: "Renforcer le respect du RGPD en apprenant à détecter les fuites potentielles de données personnelles dans les invites rédigées par l'équipe.",
        instructions: "En équipe, examinez une liste de 5 prompts rédigés par d'autres services contenant des informations sensibles (noms d'usagers en litige de cantine, adresses, plaques d'immatriculation). Modifiez ces prompts pour qu'ils soient conformes à la Charte Municipale d'usage de l'IA.",
        solution: "Exemple de prompt audité :\nAvant : 'Aide-moi à répondre à Mme Sophie Martin, habitant au 12 rue des Pins, qui conteste son amende pour chien sans laisse du 12 mars...'\nAprès : 'Aide-moi à répondre à l'administré [NOM_1] (commune de 5000 hab.) qui conteste un procès-verbal d'infraction à la réglementation des animaux domestiques dans l'espace public...'",
        reasoning: "La pseudonymisation des prompts protège l'identité des citoyens tout en permettant à l'IA d'analyser la structure légale du litige."
    },
    {
        id: 27,
        title: "Atelier Groupe : Le Duel de Rédaction d'Élus",
        support: "pc",
        format: "groupe",
        type: "efficacite",
        time: 30,
        objective: "Faire comparer à l'aveugle un texte rédigé par un agent et un texte rédigé par l'IA.",
        pedagogy: "Évaluer la qualité stylistique de l'IA et déterminer si l'humain reste indispensable pour la touche finale et l'ancrage local.",
        instructions: "Divisez le groupe en deux. Le Groupe A rédige manuellement une note de bienvenue pour les nouveaux résidents de la commune. Le Groupe B conçoit un prompt pour que l'IA rédige cette même note. Mélangez les copies et faites voter l'ensemble des stagiaires à l'aveugle sur la version la plus chaleureuse et pertinente.",
        solution: "Débriefing de l'exercice :\nSouvent, le texte de l'IA est jugé plus fluide et grammaticalement parfait, mais manque d'anecdotes locales ou de chaleur humaine. Les stagiaires concluent que la solution idéale est hybride : utiliser l'IA pour structurer et rédiger le brouillon, puis ajouter la touche humaine locale manuellement.",
        reasoning: "Cet exercice montre que l'IA est un excellent assistant rédactionnel mais ne peut pas remplacer la sensibilité culturelle et la connaissance fine des spécificités locales d'un agent public."
    },
    {
        id: 28,
        title: "Atelier Groupe : Le Livret d'Accueil du Service",
        support: "pc",
        format: "groupe",
        type: "pratique",
        time: 40,
        objective: "Rédiger en équipe le livret d'accueil des nouveaux stagiaires de la collectivité.",
        pedagogy: "Utiliser l'IA pour compiler des informations disparates du service en un document d'accueil unique cohérent.",
        instructions: "En groupes de 4, rassemblez les informations de base de vos services (horaires, codes d'accès, emplacement des bureaux, outils informatiques principaux). Demandez à l'IA de concevoir la structure générale et le contenu rédigé du guide d'accueil du service.",
        solution: "Cheminement de l'atelier :\n1. Rassembler les notes éparses sur un fichier bloc-notes.\n2. Écrire le prompt en fournissant ces notes en ressources.\n3. Exiger un ton professionnel, encourageant et clair.\n4. Demander à l'IA d'insérer des listes de contrôle (checklist) pour le premier jour du stagiaire.",
        reasoning: "Cet exercice collaboratif montre comment centraliser les connaissances tacites d'une équipe pour en faire un document de transmission officiel clair."
    },
    {
        id: 29,
        title: "Atelier Groupe : Modélisation de Workflow (DSI)",
        support: "pc",
        format: "groupe",
        type: "efficacite",
        time: 35,
        objective: "Créer le schéma logique du parcours de traitement des demandes d'urbanisme.",
        pedagogy: "Apprendre à formaliser des processus administratifs complexes sous forme de diagrammes logiques structurés par l'IA.",
        instructions: "En équipe, décrivez par écrit les étapes de validation d'une demande de permis de construire. Demandez à l'IA de traduire cette description textuelle en code Mermaid.js pour générer un organigramme visuel.",
        solution: "Prompt modèle :\n[MOI] : Chef de projet urbanisme et organisation.\n[AGENT] : Expert en cartographie des processus et diagrammes Mermaid.js.\n[INFORMATION] : Génère le code d'un diagramme de flux vertical (graph TD) représentant le traitement d'un permis de construire.\n[RESSOURCES] : Étapes : Réception dossier ➔ Vérification complétude (si incomplet ➔ renvoi usager) ➔ Instruction technique ➔ Avis du Maire ➔ Notification finale.\n[EXIGENCE] : Utilise exclusivement la syntaxe Mermaid.js standard, sans commentaires textuels en dehors du code.",
        reasoning: "La modélisation de processus par l'IA sous forme de code visualisable (Mermaid) permet de créer des organigrammes professionnels instantanément pour les manuels de procédure de la mairie."
    },
    {
        id: 30,
        title: "Atelier Groupe : Campagne de Civisme (Humour)",
        support: "pc",
        format: "groupe",
        type: "fun",
        time: 25,
        objective: "Créer 3 slogans municipaux percutants contre les incivilités canines.",
        pedagogy: "Apprendre à générer des idées de communication engageantes en exploitant le registre de l'humour ou de la surprise sémantique.",
        instructions: "En équipe, créez un prompt demandant à l'IA de concevoir 5 slogans humoristiques et percutants pour une campagne d'affichage municipale incitant les propriétaires de chiens à ramasser les déjections sur les trottoirs.",
        solution: "Prompt modèle :\n[MOI] : Chargé de communication d'une commune touristique.\n[AGENT] : Concepteur-rédacteur publicitaire réputé pour son humour bienveillant et ses slogans accrocheurs.\n[INFORMATION] : Génère 5 slogans courts pour notre campagne d'affichage 'Trottoirs Propres'.\n[EXIGENCE] : Les slogans doivent être drôles, sans être agressifs ni vulgaires (ex: 'Votre chien ne peut pas ramasser, mais il compte sur vous'). Longueur maximale par slogan : 10 mots.",
        reasoning: "La créativité de l'IA (en température élevée) permet de renouveler les discours municipaux traditionnels souvent jugés trop austères ou moralisateurs."
    },

    // === EXERCICES SUR PAPIER (31 à 60) ===
    {
        id: 31,
        title: "Anatomie d'un Prompt M.A.I.R.E. (Papier)",
        support: "papier",
        format: "individuel",
        type: "pratique",
        time: 15,
        objective: "Structurer un prompt complet sur papier en remplissant le gabarit officiel.",
        pedagogy: "Ancrer la méthodologie de structuration des invites professionnelles en s'affranchissant du PC pour se concentrer sur la logique d'écriture.",
        instructions: "Sur votre feuille, complétez le gabarit M.A.I.R.E. pour demander à une IA de rédiger un courrier aux parents d'élèves annonçant la fermeture exceptionnelle de l'école Pasteur le vendredi suivant pour cause de travaux de chauffage.",
        solution: "Correction type rédigée sur papier :\n[M] : Je suis le directeur de l'école publique Pasteur.\n[A] : Assistant administratif spécialisé dans la communication scolaire.\n[I] : Rédige une lettre d'information aux parents.\n[R] : Motif : Travaux urgents sur la chaudière centrale. Date : Vendredi 24 novembre. Repas de cantine non facturé. Accueil minimum assuré à la maison de l'enfance.\n[E] : Lettre claire de 150 mots maximum, ton poli, rassurant mais informatif. Balise [NOM_PARENT] à conserver.",
        reasoning: "Cet exercice papier garantit que l'agent a compris l'intérêt de structurer ses consignes avant de se précipiter sur l'ordinateur."
    },
    {
        id: 32,
        title: "Dessine-moi un Embedding (Papier)",
        support: "papier",
        format: "individuel",
        type: "fun",
        time: 15,
        objective: "Placer 10 mots municipaux sur un graphique vectoriel 2D.",
        pedagogy: "Visualiser spatialement le fonctionnement mathématique d'un espace vectoriel de mots (Embeddings) et comprendre la proximité sémantique.",
        instructions: "Tracez un repère avec deux axes sur votre feuille : Axe X (Hiérarchie/Pouvoir) et Axe Y (Services Techniques vs Administratifs). Positionnez les 10 mots suivants : 'Maire', 'Mairie', 'Balai', 'Pelle', 'Secrétaire', 'Adjoint', 'Tondeuse', 'Délibération', 'Nid-de-poule', 'Banane'. Expliquez pourquoi 'Banane' est rejeté.",
        solution: "Correction type :\n- En haut à droite (Pouvoir + Admin) : 'Maire', 'Adjoint', 'Délibération'.\n- En haut à gauche (Pouvoir + Technique) : 'DGS Technique' (si ajouté) ou 'Adjoint aux travaux'.\n- En bas à droite (Admin + Faible pouvoir) : 'Secrétaire', 'Mairie'.\n- En bas à gauche (Technique + Faible pouvoir) : 'Pelle', 'Balai', 'Tondeuse', 'Nid-de-poule'.\n- Banane doit être positionné à l'extrême périphérie (coordonnées neutres ou hors-sujet) car il ne partage aucune relation sémantique avec la vie administrative municipale.",
        reasoning: "Faire dessiner la carte sémantique permet aux stagiaires de comprendre visuellement que l'IA ne 'comprend' pas les mots comme un humain, mais calcule des distances géométriques entre eux."
    },
    {
        id: 33,
        title: "Anonymisation de Courrier Public (RGPD Papier)",
        support: "papier",
        format: "individuel",
        type: "pratique",
        time: 10,
        objective: "Identifier et caviarder manuellement les données personnelles d'un texte.",
        pedagogy: "Prendre l'habitude d'anonymiser systématiquement les données sensibles avant toute saisie dans une IA publique.",
        instructions: "Sur la feuille distribuée contenant le mail de demande de logement social d'un habitant (contenant : Nom, Prénom, adresse, numéro de téléphone, situation de handicap, composition familiale), barrez au feutre noir toutes les données nominatives et remplacez-les par des balises génériques (ex: [NOM_1], [TEL_1]).",
        solution: "Correction type :\n- 'Monsieur Jean Deprez' ➔ 'Monsieur [NOM_1]'\n- 'demeurant au 14 rue des Ormes' ➔ 'demeurant au [ADRESSE_1]'\n- 'joignable au 06 12 34 56 78' ➔ 'joignable au [TELEPHONE_1]'\n- La mention de la maladie ou du handicap doit être généralisée en 'situation de fragilité médicale' pour préserver le secret médical.",
        reasoning: "L'anonymisation papier ancre le respect du secret professionnel et du RGPD dans l'esprit des agents comme une étape préalable non négociable."
    },
    {
        id: 34,
        title: "L'Arbre de Décision Logique d'Aide Sociale (Papier)",
        support: "papier",
        format: "individuel",
        type: "pratique",
        time: 15,
        objective: "Écrire un algorithme symbolique strict sous forme de règles 'SI / ALORS'.",
        pedagogy: "Comprendre la différence entre l'IA symbolique (règles codées par l'humain) et l'IA numérique (apprentissage statistique).",
        instructions: "Sur papier, concevez un arbre de décision strict pour l'attribution d'une aide financière communale de cantine. L'aide est accordée SI le quotient familial est inférieur à 600€, ET SI la famille réside dans la commune, ET SI l'enfant est scolarisé en primaire. Tracez les flèches de décision.",
        solution: "Correction type :\n- Étape 1 : Quotient < 600€ ? ➔ OUI (continuer) / NON (Aide refusée).\n- Étape 2 : Résident de la commune ? ➔ OUI (continuer) / NON (Aide refusée).\n- Étape 3 : Scolarisé en primaire ? ➔ OUI (Aide accordée) / NON (Aide refusée).\nLeçon : C'est de l'IA symbolique. Si une règle change (ex. 601€ de quotient), la machine refuse l'aide de manière stricte sans étudier le contexte global humain.",
        reasoning: "Cet exercice montre les limites de la logique pure codée à la main face à la complexité des dossiers sociaux du monde réel."
    },
    {
        id: 35,
        title: "Le Devineur de Température de l'IA (Papier)",
        support: "papier",
        format: "individuel",
        type: "fun",
        time: 10,
        objective: "Identifier la température d'une réponse d'IA à partir de deux textes fournis.",
        pedagogy: "Comprendre le rôle du curseur de température sur la créativité et la fiabilité factuelle des textes générés.",
        instructions: "On vous distribue deux réponses d'une IA à qui on a demandé d'écrire un slogan pour la bibliothèque municipale. Réponse A : 'La bibliothèque : votre espace de lecture public ouvert du lundi au vendredi'. Réponse B : 'Voyagez à travers les galaxies de l'esprit, là où les livres chuchotent des secrets éternels'. Déterminez quelle réponse correspond à une température basse (0.1) et quelle réponse correspond à une température élevée (0.9).",
        solution: "Correction type :\n- Réponse A ➔ Température basse (0.1). L'IA est restée ultra-factuelle, prévisible et standard.\n- Réponse B ➔ Température élevée (0.9). L'IA a choisi des mots plus rares et métaphoriques, s'autorisant de l'audace poétique au détriment de l'information brute (les horaires).",
        reasoning: "Comprendre ce paramètre permet d'ajuster l'outil informatique : température basse pour le juridique et le budget, température haute pour la communication et le brainstorming."
    },
    {
        id: 36,
        title: "Fact-checking Juridique de Note d'Instruction (Papier)",
        support: "papier",
        format: "individuel",
        type: "efficacite",
        time: 15,
        objective: "Repérer des doutes factuels dans un rapport de synthèse fourni.",
        pedagogy: "Développer le sens critique indispensable de l'auditeur public. L'IA ne doit jamais être crue sur parole pour les textes réglementaires.",
        instructions: "On vous distribue une note rédigée par une IA sur les règles d'abattage d'arbres remarquables sur l'espace public. Lisez la note et entourez en rouge toutes les affirmations juridiques, numéros d'articles ou pourcentages qui vous semblent nécessiter une vérification manuelle obligatoire.",
        solution: "Correction type :\nLe stagiaire doit entourer : les références d'articles de loi (ex: 'Selon l'article L.123-4...'), les pourcentages d'amende (ex: 'amende de 135 €'), et les exceptions d'urgence. Il doit écrire en marge la source officielle à consulter pour valider ces points (ex: Code de l'Urbanisme, site Légifrance).",
        reasoning: "Ancrer la posture de responsabilité de l'agent : l'IA propose, l'humain dispose et valide légalement le texte final."
    },
    {
        id: 37,
        title: "Calcul de Coût en Tokens d'une API Municipale (Papier)",
        support: "papier",
        format: "individuel",
        type: "efficacite",
        time: 15,
        objective: "Calculer le coût financier d'une campagne de requêtes automatiques.",
        pedagogy: "Comprendre l'économie des modèles d'IA facturés à l'usage (au token) pour évaluer la rentabilité d'un projet d'API municipale.",
        instructions: "Une commune souhaite envoyer 5 000 courriels personnalisés de relance fiscale en utilisant l'API de ChatGPT. Chaque courriel généré consomme 500 tokens d'entrée (le prompt) et 300 tokens de sortie (le mail rédigé). Le coût de l'API est de 5$ par million de tokens d'entrée, et de 15$ par million de tokens de sortie. Calculez le coût total de la campagne sur papier.",
        solution: "Correction type :\n1. Calcul des tokens d'entrée : 5 000 x 500 = 2 500 000 tokens. Coût entrée : (2 500 000 / 1 000 000) x 5$ = 12,50$.\n2. Calcul des tokens de sortie : 5 000 x 300 = 1 500 000 tokens. Coût sortie : (1 500 000 / 1 000 000) x 15$ = 22,50$.\n3. Coût total : 12,50$ + 22,50$ = 35,00$.\nLeçon : C'est très économique par rapport au coût de saisie humaine, mais attention à la gestion des prompts longs.",
        reasoning: "Cet exercice de calcul concret démystifie la tarification invisible du cloud public pour les gestionnaires administratifs."
    },
    {
        id: 38,
        title: "Écriture de System Prompt de Guidage (Papier)",
        support: "papier",
        format: "individuel",
        type: "pratique",
        time: 15,
        objective: "Écrire les consignes de cadrage d'un assistant virtuel de bibliothèque.",
        pedagogy: "Apprendre à formuler des contraintes d'exclusion ('ne pas faire') pour maîtriser le comportement d'une IA.",
        instructions: "Rédigez sur papier le System Prompt d'un assistant IA chargé d'aider les usagers de la bibliothèque à trouver des livres. L'assistant ne doit jamais parler de politique, ne doit jamais recommander de livres à caractère violent, et doit s'exprimer dans un langage adapté aux enfants.",
        solution: "Correction type :\n'Tu es l'assistant de lecture de la bibliothèque municipale. Ta mission est de recommander des livres adaptés à l'âge de l'usager. Contraintes strictes : 1) Ne réponds à aucune question sur la politique ou les religions. 2) Interdiction absolue de suggérer des ouvrages d'horreur ou de violence extrême. 3) Si l'usager a moins de 12 ans, utilise des phrases courtes, simples et enthousiastes. 4) Reste neutre et courtois.'",
        reasoning: "Formuler des interdits clairs évite les dérives sémantiques ou les réponses hors-sujet de la machine."
    },
    {
        id: 39,
        title: "Le Traducteur Stupide des Années 70 (Papier)",
        support: "papier",
        format: "individuel",
        type: "fun",
        time: 10,
        objective: "Traduire littéralement des expressions françaises idiomatiques pour comprendre la supériorité des Transformers.",
        pedagogy: "Comprendre l'évolution historique des modèles d'IA : d'une traduction mot-à-mot logique à une analyse contextuelle globale (Transformers).",
        instructions: "Traduisez littéralement en anglais sur votre feuille les expressions suivantes comme le ferait une vieille IA sans contexte : 'Poser un lapin', 'Mettre la clé sous la porte', 'Avoir du pain sur la planche'. Expliquez la différence avec les IA modernes.",
        solution: "Correction type :\n- Traduction littérale : 'To put a rabbit', 'To put the key under the door', 'To have bread on the board'. Cela ne veut rien dire en anglais.\n- IA Moderne (Transformer) : Traduit le sens et le contexte : 'To stand someone up', 'To go out of business', 'To have a lot on one's plate'.\nExplication : Les IA modernes analysent l'ensemble de la phrase d'un coup grâce au mécanisme d'attention (2017), là où les anciens systèmes traduisaient mot après mot de manière logique mais aveugle.",
        reasoning: "Cette analogie amusante illustre le saut technologique qui a permis l'émergence des LLM récents."
    },
    {
        id: 40,
        title: "Désescalade Factuelle de Conflit de Voisinage (Papier)",
        support: "papier",
        format: "individuel",
        type: "pratique",
        time: 15,
        objective: "Nettoyer un signalement agressif pour n'en garder que la substance technique exploitable par les services.",
        pedagogy: "Apprendre à extraire des faits objectifs d'un texte chargé d'émotions négatives.",
        instructions: "On vous donne le mot papier d'un riverain agressif : 'Vos éboueurs sont des bons à rien, ils ont renversé ma poubelle devant le 10 rue des Fleurs et mon allée est dégueulasse ! C'est inadmissible, je paie mes impôts !'. Réécrivez ce message sur votre feuille de manière totalement neutre et technique pour le transmettre aux agents de collecte.",
        solution: "Correction type :\n'Signalement : Incident de collecte des déchets.\nLieu : Devant le 10 rue des Fleurs.\nProblème : Conteneur à ordures ménagères renversé sur la chaussée lors du passage de la benne de collecte. Déchets éparpillés sur le trottoir.\nAction requise : Passage d'une équipe de nettoyage de la voirie.'",
        reasoning: "Ce travail d'épuration sémantique est identique à ce qu'on demande à l'IA d'exécuter pour préserver le calme et l'efficacité des agents opérationnels."
    },
    {
        id: 41,
        title: "Correction d'Erreurs de Prompt (Papier)",
        support: "papier",
        format: "individuel",
        type: "pratique",
        time: 15,
        objective: "Identifier les manques de structure dans 3 exemples de prompts réels inefficaces.",
        pedagogy: "Diagnostiquer pourquoi un prompt échoue pour apprendre à rédiger des requêtes performantes du premier coup.",
        instructions: "Sur votre feuille, analysez ces 3 prompts : 1) 'Fais-moi un rapport sur le budget', 2) 'Rédige une lettre de refus de crèche polie', 3) 'Corrige ce texte : [Texte]'. Indiquez pour chacun l'élément manquant de la méthode MAIRE et réécrivez-les pour les corriger.",
        solution: "Correction type :\n1. Manque : [Moi], [Ressources], [Exigence]. Correction : 'Je suis adjoint aux finances, rédige une note de synthèse à partir de ce fichier Excel budgétaire...'\n2. Manque : [Ressources] (pourquoi refuse-t-on le dossier ? barème, manque de places ?). Correction : 'Refuse le dossier en indiquant que la capacité maximale de la crèche Pasteur (60 places) est atteinte...'\n3. Manque : [Exigence] (quelle correction ? orthographe simple, style, longueur ?). Correction : 'Corrige uniquement les fautes d'orthographe et de grammaire sans modifier le style ni le vocabulaire.'",
        reasoning: "Apprendre à repérer les prompts vagues permet aux stagiaires de comprendre l'origine des réponses floues ou hors-sujet de l'IA."
    },
    {
        id: 42,
        title: "Calcul de TCO sur 3 ans : Local vs Cloud (Papier)",
        support: "papier",
        format: "individuel",
        type: "efficacite",
        time: 15,
        objective: "Calculer et comparer la trajectoire financière de deux options de déploiement de l'IA.",
        pedagogy: "Ancrer les notions de budget d'investissement (CapEx) et de fonctionnement (OpEx) appliquées à l'IA.",
        instructions: "Une collectivité de 100 agents hésite entre : Option A (Achat d'un serveur local pour 20 000 € d'investissement de départ + 3 000 €/an de maintenance et électricité) et Option B (100 abonnements cloud à 15 €/agent/mois, sans investissement initial). Calculez le coût cumulé de chaque option sur 3 ans et déterminez l'option la plus économique.",
        solution: "Correction type :\n- Option A (IA Locale) : 20 000 € (Investissement) + (3 ans x 3 000 €) = 29 000 € sur 3 ans.\n- Option B (IA Cloud) : 100 agents x 15 € x 12 mois x 3 ans = 54 000 € sur 3 ans.\nConclusion : L'Option A (IA Locale) est plus économique sur 3 ans, permettant d'économiser 25 000 € tout en garantissant la souveraineté totale des données (RGPD).",
        reasoning: "Cette démonstration mathématique sur papier montre l'intérêt financier à moyen terme des architectures souveraines pour les collectivités d'une certaine taille."
    },
    {
        id: 43,
        title: "Schéma d'une Boucle Agentique ReAct (Papier)",
        support: "papier",
        format: "individuel",
        type: "pratique",
        time: 10,
        objective: "Dessiner le logigramme de fonctionnement d'un agent autonome d'IA.",
        pedagogy: "Comprendre les étapes de pensée et d'exécution d'un agent pour mieux collaborer avec lui et comprendre ses temps de calcul.",
        instructions: "Tracez un schéma circulaire représentant les 4 étapes de la boucle ReAct de l'agent : 1) Pensée (Thought), 2) Action (Action), 3) Observation (Observation), 4) Correction/Ajustement (Feedback). Donnez un exemple d'application pour chaque étape.",
        solution: "Correction type :\n- 1. Pensée : 'Pour créer le fichier, je dois utiliser l'outil d'écriture de fichier.'\n- 2. Action : Exécution de l'outil d'écriture de code dans `app.js`.\n- 3. Observation : Le système renvoie un message 'Erreur de syntaxe à la ligne 5'.\n- 4. Correction : 'Je vais corriger la ligne 5 en ajoutant le caractère manquant.'\nLe schéma doit former une boucle fermée montrant l'évaluation autonome.",
        reasoning: "Dessiner la boucle permet d'assimiler le concept de boucle de rétroaction active, qui différencie un agent d'un simple chat linéaire."
    },
    {
        id: 44,
        title: "Le Bilan Carbone d'une Requête d'IA (Papier)",
        support: "papier",
        format: "individuel",
        type: "efficacite",
        time: 15,
        objective: "Calculer l'empreinte environnementale comparée d'une recherche simple et d'une requête IA.",
        pedagogy: "Sensibiliser les stagiaires aux enjeux d'éco-responsabilité liés au numérique et à l'usage raisonné des technologies génératives.",
        instructions: "Une recherche sur Google consomme 0,0003 kWh. Une requête complexe sur un grand modèle d'IA (type GPT-4) consomme environ 0,01 kWh (soit 30 fois plus). Calculez la consommation électrique annuelle d'un service de 20 agents effectuant chacun 30 requêtes par jour (220 jours travaillés par an) sur l'IA par rapport à Google. Déduisez-en l'équivalent en km parcourus en voiture électrique (1 kWh = 6 km).",
        solution: "Correction type :\n1. Nombre de requêtes totales par an : 20 agents x 30 requêtes/jour x 220 jours = 132 000 requêtes/an.\n2. Consommation IA : 132 000 x 0,01 kWh = 1 320 kWh/an.\n3. Consommation Google : 132 000 x 0,0003 kWh = 39,6 kWh/an.\n4. Surconsommation de l'IA : 1 280,4 kWh/an.\n5. Équivalent en voiture électrique : 1 320 kWh x 6 km = 7 920 km (soit un aller-retour Paris-Moscou).\nLeçon : Utiliser l'IA de manière ciblée pour des tâches complexes et non pour des recherches simples de définition.",
        reasoning: "Le calcul de l'impact écologique ancre la sobriété numérique dans la pratique quotidienne des agents publics territoriaux."
    },
    {
        id: 45,
        title: "Le QCM de Conformité de l'AI Act (Papier)",
        support: "papier",
        format: "individuel",
        type: "pratique",
        time: 10,
        objective: "Classer 5 cas d'usage d'IA dans les catégories de risque de la réglementation européenne.",
        pedagogy: "Assimiler les obligations légales du règlement européen sur l'IA (AI Act) avant de lancer un projet municipal.",
        instructions: "Pour chacun des 5 projets municipaux suivants, indiquez s'il est classé en risque 'Inacceptable' (Interdit), 'Haut Risque' (Très régulé), 'Risque Limité' (Transparence obligatoire) ou 'Risque Minimal' (Libre) : 1) Tri automatique des candidatures de recrutement des agents de mairie, 2) Vidéosurveillance algorithmique de détection des dépôts sauvages, 3) Chatbot d'accueil des usagers du site web, 4) Correcteur d'orthographe des mails de cabinet, 5) Système de notation sociale des citoyens selon leur civisme.",
        solution: "Correction type :\n1. Recrutement automatique ➔ Haut Risque (Régulé : risque de discrimination sexiste/raciste).\n2. Vidéosurveillance algorithmique ➔ Haut Risque / Inacceptable (très encadré par dérogation préfectorale).\n3. Chatbot d'accueil usager ➔ Risque Limité (obligation d'afficher la mention 'Vous discutez avec une IA').\n4. Correcteur orthographe ➔ Risque Minimal (Usage libre).\n5. Notation sociale ➔ Inacceptable (Strictement interdit en Europe).",
        reasoning: "Ce test valide la compréhension du cadre éthique et légal européen régissant les déploiements d'IA par les pouvoirs publics."
    },
    {
        id: 46,
        title: "Atelier Groupe : Le Téléphone Arabe de l'Information (Fun)",
        support: "papier",
        format: "groupe",
        type: "fun",
        time: 15,
        objective: "Mesurer la perte de fidélité de la transmission d'information humaine.",
        pedagogy: "Mettre en évidence notre faillibilité biologique de mémorisation et de transmission pour apprécier la rigueur de réplication textuelle de l'IA.",
        instructions: "Le formateur chuchote à l'oreille d'un premier stagiaire une consigne complexe de 4 lignes contenant des dates, des lieux et des contraintes d'horaires. Chaque stagiaire doit la chuchoter à son voisin à l'oreille sans répéter. Le dernier stagiaire écrit le message final sur la feuille. Comparez le message de départ et le message d'arrivée. Calculez le taux de perte.",
        solution: "Correction / Analyse de l'atelier :\n- Message initial : 'Le Conseil Municipal se tiendra le 14 novembre à 18h30 dans la salle des fêtes de Pasteur, avec à l'ordre du jour la rénovation de l'église (budget 150 000€) et les travaux du pont des Fleurs.'\n- Message final type : 'Réunion Pasteur le 14 pour des fleurs et l'église à 15 000€.'\nAnalyse : Perte de 70% des informations et falsification du budget (divisé par 10). L'humain filtre et déforme l'information involontairement sous l'effet de l'attention sélective. L'IA, elle, réplique et transmet l'information textuelle brute avec une fidélité de 100%.",
        reasoning: "Cet exercice physique et ludique prouve aux stagiaires qu'ils ont besoin d'outils structurés (comme l'IA) pour archiver, synthétiser et transmettre des données complexes sans distorsion sémantique."
    },
    {
        id: 47,
        title: "Atelier Groupe : L'Ordinateur Humain (Jeu de rôle)",
        support: "papier",
        format: "groupe",
        type: "fun",
        time: 20,
        objective: "Comprendre le fonctionnement d'un processeur et de la mémoire vive.",
        pedagogy: "Démystifier le matériel informatique en faisant mimer le parcours d'une donnée par les stagiaires.",
        instructions: "Divisez le groupe de 4 : un joueur joue le Rôle de l'Utilisateur (qui donne une consigne papier), un joueur joue le CPU (qui applique des calculs logiques simples), un joueur joue la RAM (qui stocke les résultats temporaires sur des post-its), et un joueur joue le Disque Dur (qui conserve la base de données finale). Exécutez le calcul d'une moyenne de notes sur papier.",
        solution: "Déroulement de l'exercice :\n1. L'Utilisateur donne les notes : 12, 14, 16.\n2. Le CPU demande à la RAM de noter les chiffres sur des post-its séparés.\n3. Le CPU calcule la somme (12+14+16 = 42) et demande à la RAM de l'écrire.\n4. Le CPU divise par 3 (42/3 = 14).\n5. Le CPU demande au Disque Dur d'écrire de manière permanente le résultat 'Moyenne = 14' dans le cahier.\nLeçon : Un ordinateur fonctionne de manière séquentielle et segmentée, chaque composant ayant un rôle physique strict.",
        reasoning: "Comprendre l'architecture matérielle aide à saisir le concept d'inférence et les limites physiques (comme le goulot d'étranglement de la mémoire)."
    },
    {
        id: 48,
        title: "Atelier Groupe : Débat Mouvant Éthique & IA",
        support: "papier",
        format: "groupe",
        type: "pratique",
        time: 30,
        objective: "Débattre et se positionner sur les risques démocratiques et de souveraineté de l'IA.",
        pedagogy: "Développer une posture réflexive et nuancée face aux bouleversements technologiques dans le service public.",
        instructions: "Le formateur énonce une affirmation polémique (ex: 'L'IA va remplacer 30% des agents administratifs d'ici 5 ans' ou 'Utiliser ChatGPT en mairie devrait être interdit par la loi'). Les stagiaires se déplacent physiquement sur une ligne tracée au sol : à gauche s'ils sont 'D'accord', à droite s'ils sont 'Désaccord', au centre s'ils sont 'Neutres'. Chacun leur tour, ils expliquent leur position et peuvent faire bouger les autres.",
        solution: "Déroulement du débat :\nL'objectif n'est pas d'avoir une réponse unique, mais de confronter les arguments : gains de productivité pour se recentrer sur l'accueil humain vs risques de déshumanisation, souveraineté numérique européenne (Mistral) vs hégémonie américaine (OpenAI/Cloud Act). Le formateur note les arguments sur le tableau.",
        reasoning: "La confrontation bienveillante d'idées permet d'accompagner le changement technologique en écoutant les craintes des agents."
    },
    {
        id: 49,
        title: "Atelier Groupe : Tri de Projets AI Act (Papier)",
        support: "papier",
        format: "groupe",
        type: "pratique",
        time: 25,
        objective: "Évaluer la faisabilité réglementaire de 4 projets d'IA municipaux.",
        pedagogy: "Appliquer concrètement le cadre de l'AI Act européen sur des projets d'urbanisme, de sécurité et d'éducation de la commune.",
        instructions: "En groupe, tracez la pyramide des risques de l'AI Act sur une grande feuille. Positionnez des cartes décrivant 4 projets municipaux réels : 1) Analyse automatique de la fatigue des agents routiers par caméra thermique, 2) Attribution automatisée des logements sociaux par algorithme prédictif, 3) Caméra intelligente de comptage des vélos pour les pistes cyclables, 4) Détection des fuites d'eau par capteurs de pression intelligents. Justifiez vos choix de classification réglementaire.",
        solution: "Correction type :\n- Projet 1 (Fatigue agents) ➔ Haut Risque (Surveillance de l'emploi, risque d'atteinte aux droits des travailleurs).\n- Projet 2 (Logement social) ➔ Haut Risque (Attribution d'aides sociales et accès à des services essentiels).\n- Projet 3 (Comptage vélos) ➔ Risque Minimal (Données anonymes de trafic, pas d'identification de personnes).\n- Projet 4 (Fuites d'eau) ➔ Risque Minimal (Maintenance d'infrastructure non humaine).\nConclusion : Les projets 1 et 2 nécessiteront un audit de conformité lourd et une supervision humaine stricte avant tout déploiement.",
        reasoning: "Cet exercice opérationnel évite de lancer des projets d'IA municipaux illégaux ou soumis à des amendes européennes majeures."
    },
    {
        id: 50,
        title: "Atelier Groupe : Duel de Vitesse Écrite (IA vs Humain)",
        support: "papier",
        format: "groupe",
        type: "efficacite",
        time: 20,
        objective: "Prendre conscience du gain de temps de rédaction sur un document administratif simple.",
        pedagogy: "Comparer physiquement la vitesse de génération et le coût humain de production de documents administratifs.",
        instructions: "Divisez la table en deux. À gauche, un stagiaire rédige à la main une note d'excuse pour fermeture de cantine scolaire. À droite, un binôme rédige un prompt MAIRE, le soumet à l'IA, et imprime le résultat. Chronométrez les deux approches. Calculez le coût en temps de travail (salaire horaire moyen de 25€/h) de chaque version.",
        solution: "Correction / Débriefing type :\n- Version manuelle : Rédigée en 12 minutes. Coût agent : (12/60) x 25 € = 5,00 €.\n- Version IA : Rédigée en 3 minutes (prompt + génération + impression). Coût agent : (3/60) x 25 € = 1,25 €.\n- Gain : 3,75 € d'économie de temps de travail par note rédigée. Multiplié par le nombre de courriers annuels, le gain de productivité pour le service s'élève à plusieurs milliers d'euros, réaffectable à l'accompagnement physique des usagers.",
        reasoning: "Traduire les minutes gagnées en coût horaire réel pour la collectivité donne une assise budgétaire concrète aux formations IA."
    },
    {
        id: 51,
        title: "Atelier Groupe : Rédaction Collaborative de la Charte IA",
        support: "papier",
        format: "groupe",
        type: "pratique",
        time: 30,
        objective: "Rédiger et négocier en groupe les 3 règles d'or de l'usage de l'IA dans leur service.",
        pedagogy: "Créer un consensus d'équipe sur les limites éthiques et la sécurité des données applicables à leur propre service quotidien.",
        instructions: "En groupe de 4, identifiez les 3 risques majeurs liés à l'usage de l'IA dans votre service (ex: secrétariat ou espaces verts). Rédigez sur une affiche les 3 règles d'or de comportement obligatoires pour y faire face (ex: 'Règle 1 : Anonymisation stricte...').",
        solution: "Correction type :\nAffiche finale de groupe contenant par exemple :\n'1. Tout texte collé dans l'IA externe doit être expurgé de tout nom d'usager.\n2. L'IA ne sert que de brouillon : interdiction de copier-coller une réponse sans relecture complète.\n3. Chaque source juridique citée par l'IA doit être vérifiée sur Légifrance ou le règlement intérieur de la mairie.'",
        reasoning: "La charte rédigée par les agents eux-mêmes est beaucoup mieux acceptée et appliquée au quotidien que des consignes imposées par la direction."
    },
    {
        id: 52,
        title: "Atelier Groupe : Le Jeu des Hallucinations (Piéger l'équipe)",
        support: "papier",
        format: "groupe",
        type: "fun",
        time: 20,
        objective: "Apprendre à repérer les biais d'autorité et les faux arguments techniques de l'IA.",
        pedagogy: "Comprendre à quel point une hallucination peut paraître crédible en faisant créer de fausses informations plausibles par les stagiaires.",
        instructions: "Chaque groupe doit rédiger sur papier 3 affirmations sur l'histoire de la commune ou sur le règlement municipal : 2 vraies et 1 fausse mais rédigée dans un style administratif ultra-crédible et convaincant (ex. citant un faux article du CGCT L. 999-99). Le groupe adverse doit identifier la fausse. Comparez les techniques de manipulation sémantique.",
        solution: "Débriefing de l'exercice :\nLes stagiaires constatent qu'il est très facile de se faire piéger par un ton formel et autoritaire (le biais d'autorité), ce qui est exactement la manière dont l'IA commet des hallucinations sémantiques.",
        reasoning: "Ce jeu développe l'esprit critique et l'attention lors de la relecture des textes générés par la machine."
    },
    {
        id: 53,
        title: "Atelier Groupe : Cartographie des Tâches Éligibles",
        support: "papier",
        format: "groupe",
        type: "efficacite",
        time: 30,
        objective: "Établir la liste des missions du service à automatiser vs à conserver à la main.",
        pedagogy: "Identifier de manière pragmatique les gains d'efficacité possibles au sein du service pour réorganiser le travail des agents.",
        instructions: "Sur une grande feuille, listez toutes les tâches hebdomadaires de votre service. Divisez la feuille en 3 colonnes : 1) Tâches 100% Humaines (Relation humaine, accueil physique, arbitrage légal), 2) Tâches Hybrides (Rédaction de courriers, rapports, synthèses, programmation), 3) Tâches à Automatiser par l'IA (Correction d'orthographe, tri de données brutes, traductions). Débâtez de la répartition.",
        solution: "Correction type :\n- 100% Humain : Médiation de conflit usager, célébration des mariages, signature officielle des marchés.\n- Hybride : Rédaction de notes d'orientation, élaboration du budget initial, création de grilles d'évaluation.\n- Automatisation IA : Traduction de brochures touristiques, correction orthographique de masse, formatage CSV.",
        reasoning: "Cet audit interne des processus rassure les agents : l'IA ne remplace pas leur cœur de métier social mais absorbe les tâches répétitives."
    },
    {
        id: 54,
        title: "Atelier Groupe : La Traduction du Silence (Prompt Vague)",
        support: "papier",
        format: "groupe",
        type: "pratique",
        time: 20,
        objective: "Analyser et lister les malentendus générés par un prompt trop court.",
        pedagogy: "Comprendre pourquoi le manque de contexte force l'IA à piocher dans des généralités moyennes (hallucinations ou clichés).",
        instructions: "Prenez le prompt suivant écrit sur papier : 'Rédige une lettre pour un problème de stationnement'. Listez sur votre feuille les 10 questions sans réponse auxquelles l'IA va devoir répondre au hasard (ex: Qui écrit ? À qui ? Quel est le problème de stationnement ? Y a-t-il une amende ? Quel est le ton ?...). Écrivez le prompt corrigé.",
        solution: "Correction type :\nLes 10 inconnues du prompt vague : 1) Qui est l'expéditeur (maire, citoyen, policier municipal) ? 2) Qui est le destinataire ? 3) Quelle est l'infraction ? 4) Quel est le montant de l'amende ? 5) Dans quelle rue ? 6) Quel est le ton attendu ? 7) Quel est le format (lettre recommandée, mail) ? 8) Quel est le délai de recours ? 9) Quelles pièces joindre ? 10) Quelle est la décision de la mairie ?\nLeçon : Sans ces réponses, l'IA va inventer (halluciner) 10 faits pour combler le vide.",
        reasoning: "Cet exercice démontre de manière logique l'exigence de contexte (le pont sensoriel du prompt) pour obtenir une réponse exploitable."
    },
    {
        id: 55,
        title: "Atelier Groupe : Le Procès de l'IA Municipale (Jeu de rôle)",
        support: "papier",
        format: "groupe",
        type: "fun",
        time: 40,
        objective: "Débattre de la souveraineté juridique et de l'efficacité opérationnelle à travers un procès fictif.",
        pedagogy: "Confronter de manière théâtrale et stimulante les visions opposées de l'IA souveraine locale vs l'IA cloud américaine.",
        instructions: "Organisez un jeu de rôle sur papier : Le Procès de l'IA. Un groupe joue l'Accusation (défenseurs de la souveraineté, du RGPD strict et de l'IA locale sur serveur physique). Un groupe joue la Défense (défenseurs du gain de temps maximal, de la flexibilité financière et de l'IA cloud des géants). Un groupe joue les Juges municipaux et doit rendre sa délibération de compromis.",
        solution: "Déroulement du jeu de rôle :\nChaque groupe rédige ses plaidoiries sur papier (durée 15 minutes), puis passe à la plaidoirie orale (3 minutes par groupe). Les juges délibèrent et rédigent un compromis : ex. adoption d'une solution hybride (serveur local pour les données de santé et l'urbanisme sensible, abonnements cloud anonymisés via passerelle pour la communication et le secrétariat général).",
        reasoning: "Le jeu de rôle théâtralisé désinhibe la parole des stagiaires et permet d'assimiler des contraintes juridiques complexes de manière mémorable."
    },
    {
        id: 56,
        title: "Atelier Groupe : L'Arbre des Conséquences (RH)",
        support: "papier",
        format: "groupe",
        type: "pratique",
        time: 25,
        objective: "Évaluer l'impact social et humain du déploiement de l'IA sur l'organisation des services.",
        pedagogy: "Projeter les mutations de compétences au sein des équipes administratives pour anticiper les besoins de formation.",
        instructions: "Tracez un tronc sur votre feuille représentant l'affirmation : 'Intégration massive de l'IA dans le service administratif'. Dessinez des branches pour les conséquences positives (gain de temps, réduction du stress de saisie, plus de temps de contact usager) et des racines pour les conditions requises (formation obligatoire, équipement, conformité RGPD). Dessinez à droite les branches mortes (tâches supprimées, ex. classement manuel).",
        solution: "Correction type :\n- Branches positives : recentrage sur l'accueil humain, revalorisation des postes d'agents, réduction des erreurs de saisie.\n- Branches mortes (obsolètes) : saisie manuelle de données brutes, rédaction de courriers administratifs répétitifs à partir de zéro.\n- Racines (conditions d'accès) : formation aux prompts, mise en place de serveurs en Europe, définition d'une charte d'utilisation claire.",
        reasoning: "Cet outil d'analyse visuelle aide les managers de collectivités à anticiper l'impact de l'IA sur leurs équipes en le visualisant."
    },
    {
        id: 57,
        title: "Calculateur de Gain Financier Annuel d'Équipe (Papier)",
        support: "papier",
        format: "groupe",
        type: "efficacite",
        time: 20,
        objective: "Calculer le retour sur investissement d'une formation IA sur une équipe de 10 agents.",
        pedagogy: "Calculer concrètement le gain financier indirect d'une montée en compétences technologiques.",
        instructions: "Une formation à l'IA fait gagner en moyenne 3 heures de saisie et de rédaction par semaine à un agent administratif. Pour une équipe de 10 agents payés en moyenne 22 € bruts de l'heure (charges comprises), calculez le gain de temps annuel en heures et en équivalent financier (sur 44 semaines travaillées par an). Comparez cela au coût d'achat d'une licence Pro annuelle à 240 € par agent.",
        solution: "Correction type :\n1. Gain de temps hebdomadaire de l'équipe : 10 agents x 3 heures = 30 heures/semaine.\n2. Gain de temps annuel de l'équipe : 30 heures x 44 semaines = 1 320 heures de travail économisées par an.\n3. Gain financier annuel indirect : 1 320 heures x 22 € = 29 040 € d'économie de temps de travail par an.\n4. Coût des licences Pro pour l'équipe : 10 agents x 240 € = 2 400 € / an.\nConclusion : Le gain de productivité annuel (29 040 €) est plus de 12 fois supérieur au coût d'acquisition des licences d'IA Pro (2 400 €). Le retour sur investissement est immédiat pour la collectivité.",
        reasoning: "La traduction des gains de temps en indicateurs financiers objectifs permet de valider le budget de formation auprès des élus et du DGS."
    },
    {
        id: 58,
        title: "Le Jeu de Cartes des Alliances d'IA (Papier)",
        support: "papier",
        format: "groupe",
        type: "fun",
        time: 15,
        objective: "Associer correctement les acteurs mondiaux de l'IA à leurs modèles et spécificités juridiques.",
        pedagogy: "Cartographier la géopolitique de l'IA de manière ludique sur table pour retenir qui fait quoi et sous quelle souveraineté.",
        instructions: "Sur des post-its découpés sur table, associez chaque 'Acteur' (OpenAI, Microsoft, Google, Anthropic, Mistral AI) à sa 'Nationalité/Hébergement' (États-Unis/Cloud Act vs France/Souverain), son 'Modèle' (GPT, Gemini, Claude, Mistral) et sa 'Cible' (Bureautique intégrée, Grand public, Entreprises sécurisées, Hébergement local).",
        solution: "Correction type :\n- OpenAI ➔ États-Unis ➔ GPT ➔ Grand public & Grand volume.\n- Microsoft ➔ États-Unis ➔ Copilot ➔ Bureautique Office / Windows.\n- Google ➔ États-Unis ➔ Gemini ➔ Recherche web & Efficacité TPU.\n- Anthropic ➔ États-Unis ➔ Claude ➔ Sécurité d'écriture & Contextes longs.\n- Mistral AI ➔ France ➔ Codestral / Mistral Large ➔ Souveraineté européenne & Modèles hébergeables localement.",
        reasoning: "La manipulation de post-its sur table ancre la mémoire visuelle et clarifie le marché géopolitique de l'IA pour les décideurs."
    },
    {
        id: 59,
        title: "Cartographie RGPD du Trajet de la Donnée (Papier)",
        support: "papier",
        format: "groupe",
        type: "pratique",
        time: 30,
        objective: "Dessiner le trajet d'un courriel d'administré pour vérifier sa conformité RGPD.",
        pedagogy: "Comprendre où voyagent les données des citoyens lors de l'utilisation de serveurs cloud et identifier les fuites de souveraineté.",
        instructions: "Dessinez sur une grande feuille le trajet d'un courriel contenant un nom et un numéro d'usager. Tracez la ligne de passage à l'étranger dans deux cas : Cas A (L'agent copie-colle le texte dans ChatGPT Plus américain) et Cas B (L'agent utilise l'anonymiseur local puis envoie le texte à un serveur d'IA souverain hébergé en Europe).",
        solution: "Correction type :\n- Cas A (ChatGPT brut) : Écran PC agent ➔ Box internet ➔ Câble sous-marin Atlantique ➔ Serveurs OpenAI (États-Unis). Donnée soumise au Cloud Act et accessible par le renseignement US. Non-conforme RGPD.\n- Cas B (Anonymisé + Souverain) : Écran PC agent ➔ Anonymiseur JS local (les noms deviennent [NOM_1], la donnée ne sort pas du PC) ➔ Envoi du texte anonymisé vers un serveur hébergé à Francfort (Europe). Conforme RGPD.",
        reasoning: "Visualiser physiquement le voyage des octets à travers l'océan Atlantique responsabilise les agents sur le geste du copier-coller."
    },
    {
        id: 60,
        title: "Atelier Groupe : La Co-correction d'Évaluation (Papier)",
        support: "papier",
        format: "groupe",
        type: "efficacite",
        time: 25,
        objective: "Corriger en équipe les erreurs d'un prompt rédigé en fin de formation.",
        pedagogy: "Clore la formation en jouant le rôle de correcteurs d'invites pour consolider l'ensemble des acquis pédagogiques de la journée.",
        instructions: "On vous distribue un prompt papier rédigé par un élève fictif en fin de stage contenant plusieurs fautes graves (manque d'anonymisation d'usager, consigne floue sans contraintes de format, ton inadapté). Corrigez le texte en rouge et réécrivez le prompt d'examen parfait.",
        solution: "Correction type :\nLe prompt fautif contenait : 'Rédige une lettre de relance de facture de cantine de 50€ pour Mme Deprez Julie'.\nLes stagiaires doivent entourer et corriger : 1) 'Mme Deprez Julie' ➔ Doit être remplacé par '[NOM_1]'. 2) 'Rédige une lettre' ➔ Manque [Moi], [Agent], [Exigence].\nRéécriture correcte : '[MOI] Je suis comptable en mairie... [AGENT] Agis en médiateur financier... [INFORMATION] Conçois une lettre de rappel de paiement pour l'administré [NOM_1]... [RESSOURCES] Facture de cantine scolaire impayée de 50€... [EXIGENCE] Lettre de 150 mots maximum, ton ferme mais respectueux. Indique les modes de paiement (chèque, virement, TIPI).'",
        reasoning: "Devenir correcteur d'invites est le meilleur moyen de valider l'autonomie rédactionnelle des agents à l'issue de leur parcours de formation."
    }
];

// Export logic for browser environment
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { EXERCISES_DATABASE };
}
